export type ProjectDetail = {
  slug: string;
  title: string;
  eyebrow: string;
  description: string;
  image?: string;
  imageAlt?: string;
  category: string;
  status: string;
  platforms: string;
  repository?: string;
  private?: boolean;
  specialAccess?: boolean;
  requestHref?: string;
  requestLabel?: string;
  tags: string[];
  purpose: string;
  features: [string, string, string, string];
  screenshots?: { src: string; alt: string; label: string }[];
  journalSlug?: string;
};

export const projectDetails: ProjectDetail[] = [
  { slug: "the-islamic-dilemma", title: "The Islamic Dilemma", eyebrow: "Faith-based research application", description: "An offline-first Android research workspace examining the Qur’an’s relationship to the Torah and Gospel through Bible evidence, Qur’anic passages, manuscripts, lexical study, and carefully identified reference material.", image: "/projects/islamic-dilemma-banner.png", imageAlt: "The Islamic Dilemma research application artwork", category: "Faith-Based", status: "Test build", platforms: "Android", repository: "https://github.com/mcographics/Islamic-Dilemma-Test-Builds", private: true, tags: ["Android", "React", "Offline research"], purpose: "A private place to examine difficult religious questions with sources kept visible. The project is designed around local reading and research rather than a cloud account or a feed of untraceable claims.", features: ["Bible and Qur’an references", "Manuscript-aware research", "Hebrew and Greek lexical study", "Offline-first Android reading"], screenshots: [
    { src: "/projects/islamic-dilemma-screens/01-home.png", label: "Home", alt: "Islamic Dilemma Android app home screen" },
    { src: "/projects/islamic-dilemma-screens/02-dilemmas.png", label: "Dilemmas", alt: "Islamic Dilemma Android app dilemmas screen" },
    { src: "/projects/islamic-dilemma-screens/03-compare.png", label: "Compare", alt: "Islamic Dilemma Android app comparison screen" },
    { src: "/projects/islamic-dilemma-screens/04-evidence.png", label: "Evidence", alt: "Islamic Dilemma Android app evidence library screen" },
  ] },
  { slug: "unified-ai-studio", title: "Unified AI Studio", eyebrow: "Creative software suite", description: "A modular AI-powered workspace for transforming images, video, and visual media through generation, reconstruction, and cinematic workflows.", image: "/projects/unified-ai-studio-logo.png", imageAlt: "Unified AI Studio logo", category: "Creative", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/Unified-Ai-Studio", private: true, tags: ["Python", "PySide6", "AI tools"], purpose: "Unified AI Studio brings creative tools into one deliberate workspace. Its direction is practical: make powerful media workflows easier to understand, compose, and keep under the creator’s control.", features: ["Modular creative tools", "Image and video workflows", "Local desktop operation", "Cinematic experimentation"] },
  { slug: "fierolink-gt", title: "FieroLink GT", eyebrow: "Pontiac Fiero vehicle intelligence app", description: "A local-first Windows vehicle intelligence platform for 1984–1988 Pontiac Fiero models, combining ALDL data capture, live instrumentation, diagnostics, maintenance tracking, performance telemetry, and reference manuals.", image: "/projects/fierolink-gt-1988.jpeg", imageAlt: "1988 Pontiac Fiero GT project vehicle used for FieroLink GT", category: "Apps", status: "In development", platforms: "Windows", specialAccess: true, requestHref: "/about#connect", requestLabel: "Request Required", tags: ["Electron", "React", "ALDL diagnostics"], purpose: "FieroLink GT is being built as a contained vehicle-intelligence workspace for 1984–1988 Pontiac Fiero owners, mechanics, and enthusiasts. It connects to the factory GM ECM through the Assembly Line Diagnostic Link (ALDL) to retrieve and log whatever engine-management data the original computer makes available. An optional auxiliary sensor module can add visibility for systems the factory ECM cannot monitor. The app brings those readings together with live digital instrumentation, diagnostic records, maintenance tracking, performance telemetry, anomaly detection, historical trends, and an AI-assisted troubleshooting surface. When compatible tuning hardware or a replacement ECM is installed, later versions may provide calibration analysis and guarded tuning support; those functions are deliberately separate from ordinary monitoring and should never imply unrestricted write access. The goal is to give the Fiero a modern diagnostic and vehicle-management brain without erasing its original mechanical identity.", features: ["Factory ALDL ECM data capture", "Optional auxiliary sensor monitoring", "Live instrumentation and diagnostics", "Maintenance, performance, and trend history", "Anomaly detection and AI-assisted troubleshooting", "Contained manuals and Fiero reference library"] },
  { slug: "creative-whiteboard", title: "Creative Whiteboard", eyebrow: "Infinite canvas desktop app", description: "An offline-first infinite whiteboard for drawing, annotation, document review, brainstorming, visual planning, and project organization.", image: "/projects/creative-whiteboard.png", imageAlt: "Creative Whiteboard application artwork", category: "Creative", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/CreativeWhiteboard", tags: ["Electron", "React", "Infinite canvas"], purpose: "Creative Whiteboard is for ideas that do not want to be trapped in a narrow document. It combines spatial thinking with the practical tools needed to review, annotate, and organize real work.", features: ["Infinite spatial canvas", "Drawing and annotation", "Document review", "Offline-first project planning"] },
  { slug: "comic-organizer", title: "Comic Organizer", eyebrow: "Local comic archive manager", description: "A private, local-first library for finding, organizing, searching, and safely managing CBZ and CBR comic archives.", image: "/projects/comic-organizer.png", imageAlt: "Comic Organizer application artwork", category: "Apps", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/Comic-Organizer", private: true, tags: ["Electron", "React", "Local-first"], purpose: "Comic Organizer treats a personal comic collection as something worth preserving. The goal is a calm, searchable library with safe file operations and no requirement to hand a private archive to a service.", features: ["CBZ and CBR support", "Collection organization", "Fast local search", "Recoverable file management"] },
  { slug: "dossier-builder", title: "Dossier Builder", eyebrow: "Professional document workspace", description: "A secure, local-first desktop workspace for creating, structuring, editing, and exporting professional dossiers from reusable document templates.", image: "/projects/dossier-builder.png", imageAlt: "Dossier Builder application artwork", category: "Apps", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/Dosseir-Builder", tags: ["Electron", "TypeScript", "Local-first"], purpose: "Dossier Builder is built for structured documents that need more care than a blank page provides. Reusable templates, local files, and a focused editing environment keep the workflow understandable and controlled.", features: ["Reusable document templates", "Structured dossier editing", "Local document storage", "Professional export workflow"] },
  { slug: "truth-news", title: "Truth News", eyebrow: "Christian research newsroom", description: "A local-first Christian news, Scripture, history, timeline, and prophecy application built around evidence and context.", image: "/projects/truth-news.jpg", imageAlt: "Truth News application artwork", category: "Apps", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/TruthNewsApp", tags: ["React", "TypeScript", "Research"], purpose: "Truth News is intended to slow down the news cycle enough to examine sources, history, Scripture, and timelines together. It is a research surface, not a substitute for discernment.", features: ["Evidence-led news reading", "Scripture and history context", "Timeline exploration", "Local-first research workspace"] },
  { slug: "public-nuisance", title: "Public Nuisance", eyebrow: "Android live-news satire app", description: "A source-first Android news reader for Canadian and U.S. headlines, with an original GTA-style satire layer placed over verified leads until the reader opens the publisher source.", image: "/projects/public-nuisance-banner.png", imageAlt: "Public Nuisance Android news satire app banner", category: "Apps", status: "Release available", platforms: "Android", repository: "https://github.com/mcographics/REALLIFENEWS--GTA-STYLED-", tags: ["Android", "React", "Live news"], purpose: "Public Nuisance makes the news cycle readable without hiding where the facts came from. It ingests publisher feed metadata, keeps the original source link available, and separates verified reporting from deliberately crude commentary.", features: ["Live Canada and U.S. feeds", "5, 10, 15, or 20-minute refresh", "Source-linked satire reader", "GitHub APK update checks"], journalSlug: "public-nuisance-v1-1-1" },
  { slug: "re-tui", title: "Re:TUI", eyebrow: "Android launcher experiment", description: "A fork of the Re:TUI Android launcher, customized with terminal styling, widgets, modules, presets, and Termux integration.", category: "Experiments", status: "Public project", platforms: "Android", repository: "https://github.com/mcographics/Re-TUI", tags: ["Kotlin", "Android", "Terminal UI"], purpose: "Re:TUI explores what an Android home screen feels like when it behaves more like a compact command environment. It remains an experiment in launcher navigation, customization, and Termux-adjacent workflows.", features: ["Terminal-inspired launcher", "Custom widgets and modules", "Preset-based customization", "Termux integration"] },
  { slug: "bridgeforge", title: "BridgeForge", eyebrow: "Unreal and Blender ecosystem", description: "A focused ecosystem concept for Unreal Engine and Blender creators—bringing scattered tools, learning, and community resources together.", image: "/projects/bridgeforge.png", imageAlt: "BridgeForge creator ecosystem artwork", category: "Game Dev", status: "Building", platforms: "Windows", repository: "https://github.com/mcographics/BridgeForge", private: true, tags: ["Unreal Engine", "Blender", "Creator tools"], purpose: "BridgeForge is a concept for connecting the practical parts of 3D creation: tools, learning, references, and community. The project is still taking shape, so this page records the direction without pretending the full platform is released.", features: ["Unreal creator workflows", "Blender-focused resources", "Learning and reference hub", "Community ecosystem concept"] },
  { slug: "grace-seek", title: "Grace Seek", eyebrow: "Bible study desktop app", description: "A Scripture exploration app combining Bible search and reading with Strong’s lexicon, original-language datasets, and atlas-style place lookup.", image: "/projects/grace-seek.png", imageAlt: "Grace Seek Bible study application artwork", category: "Faith-Based", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/Grace-Seek", private: true, tags: ["Bible study", "Strong’s", "Local datasets"], purpose: "Grace Seek is being shaped as a serious local study companion: a way to move between the Biblical text, language references, and places without losing the reader’s sense of context.", features: ["Bible search and reading", "Strong’s lexicon references", "Original-language datasets", "Atlas-style place lookup"] },
  { slug: "space-eye", title: "Space Eye", eyebrow: "Space awareness experiment", description: "A real-time space-awareness experience that visualizes the solar system, tracks cosmic activity, and gathers public UFO and orb-sighting data.", image: "/projects/space-eye.png", imageAlt: "Space Eye visualization artwork", category: "Experiments", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/Space_Eye", private: true, tags: ["JavaScript", "Visualization", "Public data"], purpose: "Space Eye combines scientific scale with the human urge to look up and ask questions. It is an exploratory visualization project, with public data and uncertainty kept distinct where the evidence is incomplete.", features: ["Solar-system visualization", "Cosmic activity tracking", "Public sighting data", "Exploratory visual interface"] },
  { slug: "tanyaos", title: "TanyaOS", eyebrow: "AI cognitive interface", description: "A modular AI operating-system concept connecting a language model with structured memory, morality, reasoning, and autonomous decision-making subsystems.", image: "/projects/tanya-os.png", imageAlt: "TanyaOS interface artwork", category: "Experiments", status: "Research project", platforms: "Research prototype", repository: "https://github.com/mcographics/TanyaOS", private: true, tags: ["Python", "React", "Cognitive AI"], purpose: "TanyaOS is a research direction for making AI systems more structured, inspectable, and purposeful. Memory, reasoning, values, and action are treated as separate concerns that need to be understood before they are combined.", features: ["Structured memory concepts", "Reasoning subsystem research", "Values and morality layer", "Modular AI interface"] },
  { slug: "workspaces", title: "WorkSpaces", eyebrow: "All-in-one creative workspace", description: "An all-in-one creative environment combining visual canvases, brainstorming, document writing, book formatting, and story architecture.", image: "/projects/workspaces.png", imageAlt: "WorkSpaces creative environment artwork", category: "Creative", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/WorkSpaces", private: true, tags: ["TypeScript", "Writing", "Visual canvas"], purpose: "WorkSpaces is for the messy middle of making something: when notes, images, drafts, scenes, and structure need to coexist. Its purpose is to let a creator move between those modes without scattering the project across disconnected tools.", features: ["Visual project canvases", "Document and book writing", "Story architecture", "Local creative workspace"] },
  { slug: "project-database", title: "Project Database", eyebrow: "Project organization desktop app", description: "A local-first desktop workspace for organizing projects, documents, images, collections, timelines, and related creative assets in one secure place.", image: "/projects/project-database.png", imageAlt: "Project Database application artwork", category: "Apps", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/ProjectDatabase", tags: ["Electron", "React", "C++"], purpose: "Project Database gives each project a place where its files, references, timelines, and related ideas can remain connected. The foundation is local-first, so organization does not depend on a remote account.", features: ["Project and asset records", "Documents and image collections", "Timeline organization", "Secure local storage"] },
  { slug: "gamingbible", title: "GamingBible", eyebrow: "Gaming news desktop app", description: "A personalized desktop hub for gaming news, upcoming releases, studios, industry coverage, esports, hardware, and rumors—all gathered in one focused app.", image: "/projects/gamingbible.png", imageAlt: "GamingBible application artwork", category: "Apps", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/GamingBible", tags: ["Electron", "React", "Gaming news"], purpose: "GamingBible is a focused home for following the games and people that matter to a reader. It brings multiple kinds of coverage together while keeping personalization local and account-free.", features: ["Gaming news aggregation", "Release and studio tracking", "Esports and hardware coverage", "Local preferences and follows"] },
  { slug: "character-profile-maker", title: "Character Profile Maker", eyebrow: "Character design workspace", description: "A flexible character-building workspace for creating detailed visual profiles, organizing reference views, importing artwork, and exporting polished character sheets.", image: "/projects/character-profile-maker.png", imageAlt: "Character Profile Maker artwork", category: "Creative", status: "In development", platforms: "Windows", tags: ["Character design", "Worldbuilding", "Export tools"], purpose: "Character Profile Maker helps turn scattered references and design decisions into a coherent record. It is meant for creators who want their characters’ visual identity, notes, and variations in one editable workspace.", features: ["Detailed character profiles", "Reference-view organization", "Artwork importing", "Polished character-sheet export"] },
];

export const projectDetailSlugs = projectDetails.map((project) => project.slug);
