export type ProjectDetail = {
  slug: string;
  title: string;
  eyebrow: string;
  description: string;
  image?: string;
  imageAlt?: string;
  shareImage?: string;
  shareImageAlt?: string;
  category: string;
  status: string;
  platforms: string;
  repository?: string;
  upstreamRepository?: string;
  upstreamLabel?: string;
  private?: boolean;
  specialAccess?: boolean;
  requestHref?: string;
  requestLabel?: string;
  tags: string[];
  purpose: string;
  features: string[];
  featureDetails?: string[];
  screenshots?: { src: string; alt: string; label: string }[];
  screenshotEyebrow?: string;
  screenshotDescription?: string;
  release?: { version: string; downloadUrl: string; releaseUrl: string };
  releaseHeading?: string;
  releaseDescription?: string;
  releasePlatform?: string;
  releaseSmallText?: string;
  journalSlug?: string;
  journalHeading?: string;
  journalDescription?: string;
};

export const projectDetails: ProjectDetail[] = [
  { slug: "the-islamic-dilemma", title: "The Islamic Dilemma", eyebrow: "Faith-based research application", description: "An offline-first Android research workspace examining the Qur’an’s relationship to the Torah and Gospel through Bible evidence, Qur’anic passages, manuscripts, lexical study, and carefully identified reference material.", image: "/projects/islamic-dilemma-banner.png", imageAlt: "The Islamic Dilemma research application artwork", category: "Faith-Based", status: "Test build", platforms: "Android", repository: "https://github.com/mcographics/Islamic-Dilemma-Test-Builds", private: true, tags: ["Android", "React", "Offline research"], purpose: "A private place to examine difficult religious questions with sources kept visible. The project is designed around local reading and research rather than a cloud account or a feed of untraceable claims.", features: ["Bible and Qur’an references", "Manuscript-aware research", "Hebrew and Greek lexical study", "Offline-first Android reading"], screenshots: [
    { src: "/projects/islamic-dilemma-screens/01-home.png", label: "Home", alt: "Islamic Dilemma Android app home screen" },
    { src: "/projects/islamic-dilemma-screens/02-dilemmas.png", label: "Dilemmas", alt: "Islamic Dilemma Android app dilemmas screen" },
    { src: "/projects/islamic-dilemma-screens/03-compare.png", label: "Compare", alt: "Islamic Dilemma Android app comparison screen" },
    { src: "/projects/islamic-dilemma-screens/04-evidence.png", label: "Evidence", alt: "Islamic Dilemma Android app evidence library screen" },
  ] },
  { slug: "chainbreaker", title: "ChainBreaker", eyebrow: "Private Android rule of life", description: "A local-first Android application for breaking chains and building the man through Scripture, daily missions, training, reflection, and brotherhood.", image: "/projects/chainbreaker-banner.png", imageAlt: "ChainBreaker banner artwork showing broken chains held before a glowing cross", category: "Faith-Based", status: "Release available", platforms: "Android 7.0+", repository: "https://github.com/mcographics/ChainBreakerApp", tags: ["Android", "React", "KJV", "Local-first"], purpose: "ChainBreaker is a private daily operating system for the work of becoming a faithful man. Its first release keeps the loop close at hand: pray, read, act, train, reflect, and repeat, with personal progress stored locally on the device.", features: ["Daily Scripture and missions", "Offline KJV reader with search and notes", "Private battle tracking and intervention flow", "Foundation training plan", "Editorial Brotherhood library", "Local SQLite persistence"], release: { version: "0.0.4", downloadUrl: "https://github.com/mcographics/ChainBreakerApp/releases/download/v0.0.4/ChainBreaker-0.0.4.apk", releaseUrl: "https://github.com/mcographics/ChainBreakerApp/releases/tag/v0.0.4" }, journalSlug: "chainbreaker-android-mvp", journalHeading: "The first release story.", journalDescription: "Read how ChainBreaker turns Scripture, daily missions, training, reflection, and private local progress into a focused Android rule of life, now with private Settings and Android release updates.", screenshotEyebrow: "Captured from the installed signed Android release", screenshotDescription: "These are direct screenshots from ChainBreaker 0.0.4 running on a connected Samsung phone.", screenshots: [
    { src: "/projects/chainbreaker-screens-v0.0.4/01-onboarding.png", label: "Onboarding", alt: "ChainBreaker 0.0.4 Android first-run onboarding screen" },
    { src: "/projects/chainbreaker-screens-v0.0.4/02-home.png", label: "Home", alt: "ChainBreaker 0.0.4 Android Home daily operating screen" },
    { src: "/projects/chainbreaker-screens-v0.0.4/08-battle.png", label: "Home battle card", alt: "ChainBreaker 0.0.4 Android Home screen showing the active battle card" },
    { src: "/projects/chainbreaker-screens-v0.0.4/03-word.png", label: "Word", alt: "ChainBreaker 0.0.4 Android Word Bible reader" },
    { src: "/projects/chainbreaker-screens-v0.0.4/04-brotherhood.png", label: "Brotherhood", alt: "ChainBreaker 0.0.4 Android Brotherhood editorial library" },
    { src: "/projects/chainbreaker-screens-v0.0.4/05-build.png", label: "Build", alt: "ChainBreaker 0.0.4 Android Build training plan" },
    { src: "/projects/chainbreaker-screens-v0.0.4/06-my-journey.png", label: "My Journey", alt: "ChainBreaker 0.0.4 Android My Journey progress screen" },
    { src: "/projects/chainbreaker-screens-v0.0.4/07-brotherhood-article.png", label: "Article detail", alt: "ChainBreaker 0.0.4 Android Brotherhood article detail" },
    { src: "/projects/chainbreaker-screens-v0.0.4/09-battle-detail.png", label: "Battle detail", alt: "ChainBreaker 0.0.4 Android private battle detail screen" },
    { src: "/projects/chainbreaker-screens-v0.0.4/10-settings.png", label: "Settings", alt: "ChainBreaker 0.0.4 Android Settings screen" },
  ] },
  { slug: "unified-ai-studio", title: "Unified AI Studio", eyebrow: "Creative software suite", description: "A modular AI-powered workspace for transforming images, video, and visual media through generation, reconstruction, and cinematic workflows.", image: "/projects/unified-ai-studio-logo.png", imageAlt: "Unified AI Studio logo", category: "Creative", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/Unified-Ai-Studio", private: true, tags: ["Python", "PySide6", "AI tools"], purpose: "Unified AI Studio brings creative tools into one deliberate workspace. Its direction is practical: make powerful media workflows easier to understand, compose, and keep under the creator’s control.", features: ["Modular creative tools", "Image and video workflows", "Local desktop operation", "Cinematic experimentation"] },
  { slug: "fierolink-gt", title: "FieroLink GT", eyebrow: "Pontiac Fiero vehicle intelligence app", description: "A local-first Windows Fiero telemetry prototype with a simulator, receive-only GM ALDL serial transport, raw capture monitoring, and a deliberate path toward verified diagnostics.", image: "/projects/fierolink-gt-banner.png", imageAlt: "FieroLink GT wide project banner with a red Pontiac Fiero GT", shareImage: "/projects/fierolink-gt.png", shareImageAlt: "FieroLink GT project artwork with a red Pontiac Fiero GT", category: "Apps", status: "In development", platforms: "Windows", specialAccess: true, requestHref: "/about#connect", requestLabel: "Request Required", tags: ["Electron", "React", "ALDL diagnostics"], purpose: "FieroLink GT is being built as a contained vehicle-intelligence workspace for Pontiac Fiero owners, mechanics, and enthusiasts. The current Phase 3 foundation includes a simulator and a receive-only Windows ALDL transport that can discover COM ports and retain timestamped raw bytes. Real ECU identification, packet decoding, normalized telemetry, and vehicle validation remain ahead of the project. The application deliberately keeps unverified values out of the dashboard and contains no ECU write, calibration, flash, live-tuning, or trouble-code-clear commands. The goal is to develop a careful diagnostic companion without pretending that an older Fiero is a modern OBD-II vehicle.", features: ["Windows COM-port and adapter discovery", "Receive-only ALDL raw capture", "Simulation dashboard and fault scenarios", "Verified-decoder-ready telemetry architecture", "Local Fiero reference library", "Future diagnostics behind an evidence gate"], featureDetails: ["Scans for Windows serial devices and shows adapter identity hints, while leaving electrical compatibility and wiring for independent verification.", "Opens a selected port at the provisional profile rate and retains timestamped inbound bytes without sending commands to the vehicle.", "Keeps the dashboard useful for development and demonstrations through clearly labeled simulated readings and deterministic fault scenarios.", "Separates transport from decoding so packet framing, offsets, checksums, equations, units, age, and quality can be verified before values are promoted.", "Keeps supplied Fiero manuals and reference sources close to the workspace without presenting them as live telemetry evidence.", "Leaves real ECU readings and diagnostic conclusions unavailable until they have been tested against documented definitions and real vehicle captures."] },
  { slug: "creative-whiteboard", title: "Creative Whiteboard", eyebrow: "Infinite canvas desktop app", description: "An offline-first infinite whiteboard for drawing, annotation, document review, brainstorming, visual planning, and project organization.", image: "/projects/creative-whiteboard.png", imageAlt: "Creative Whiteboard application artwork", category: "Creative", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/CreativeWhiteboard", tags: ["Electron", "React", "Infinite canvas"], purpose: "Creative Whiteboard is for ideas that do not want to be trapped in a narrow document. It combines spatial thinking with the practical tools needed to review, annotate, and organize real work.", features: ["Infinite spatial canvas", "Drawing and annotation", "Document review", "Offline-first project planning"] },
  { slug: "comic-organizer", title: "Comic Organizer", eyebrow: "Local comic archive manager", description: "A private, local-first library for finding, organizing, searching, and safely managing CBZ and CBR comic archives.", image: "/projects/comic-organizer.png", imageAlt: "Comic Organizer application artwork", category: "Apps", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/Comic-Organizer", private: true, tags: ["Electron", "React", "Local-first"], purpose: "Comic Organizer treats a personal comic collection as something worth preserving. The goal is a calm, searchable library with safe file operations and no requirement to hand a private archive to a service.", features: ["CBZ and CBR support", "Collection organization", "Fast local search", "Recoverable file management"] },
  { slug: "dossier-builder", title: "Dossier Builder", eyebrow: "Professional document workspace", description: "A secure, local-first desktop workspace for creating, structuring, editing, and exporting professional dossiers from reusable document templates.", image: "/projects/dossier-builder.png", imageAlt: "Dossier Builder application artwork", category: "Apps", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/Dosseir-Builder", tags: ["Electron", "TypeScript", "Local-first"], purpose: "Dossier Builder is built for structured documents that need more care than a blank page provides. Reusable templates, local files, and a focused editing environment keep the workflow understandable and controlled.", features: ["Reusable document templates", "Structured dossier editing", "Local document storage", "Professional export workflow"] },
  { slug: "truth-news", title: "Truth News", eyebrow: "Christian research newsroom", description: "A local-first Christian news, Scripture, history, timeline, and prophecy application built around evidence and context.", image: "/projects/truth-news.jpg", imageAlt: "Truth News application artwork", category: "Apps", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/TruthNewsApp", tags: ["React", "TypeScript", "Research"], purpose: "Truth News is intended to slow down the news cycle enough to examine sources, history, Scripture, and timelines together. It is a research surface, not a substitute for discernment.", features: ["Evidence-led news reading", "Scripture and history context", "Timeline exploration", "Local-first research workspace"] },
  { slug: "public-nuisance", title: "Public Nuisance", eyebrow: "Android live-news satire app", description: "A source-first Android news reader for Canadian and U.S. headlines, with an original GTA-style satire layer placed over verified leads until the reader opens the publisher source.", image: "/projects/public-nuisance-banner.png", imageAlt: "Public Nuisance Android news satire app banner", category: "Apps", status: "Release available", platforms: "Android", repository: "https://github.com/mcographics/REALLIFENEWS--GTA-STYLED-", tags: ["Android", "React", "Live news"], purpose: "Public Nuisance makes the news cycle readable without hiding where the facts came from. It ingests publisher feed metadata, keeps the original source link available, and separates verified reporting from deliberately crude commentary.", features: ["Live Canada and U.S. feeds", "5, 10, 15, or 20-minute refresh", "Source-linked satire reader", "GitHub APK update checks"], journalSlug: "public-nuisance-v1-1-1" },
  { slug: "netrunner-launcher", title: "Netrunner-Launcher", eyebrow: "Customized Re:TUI Android launcher fork", description: "Kenneth Salmon's customized fork of DvilSpawn's Re:TUI Android launcher, preserving the original developers' command-first foundation while adding a personal red dashboard, fixed quick apps, system and weather monitoring, notification behavior, and interface changes.", image: "/projects/netrunner-launcher-banner-v1.png", imageAlt: "Red and black Netrunner-Launcher cyberpunk terminal banner", category: "Experiments", status: "Public project", platforms: "Android", repository: "https://github.com/mcographics/Netrunner-Launcher", upstreamRepository: "https://github.com/DvilSpawn/Re-TUI", upstreamLabel: "DvilSpawn/Re:TUI", tags: ["Kotlin", "Android", "Customized Re:TUI fork"], purpose: "Netrunner-Launcher is my personalized Android home environment built on DvilSpawn's Re:TUI repository, which continues Francesco Andreuzzi's original T-UI Console Launcher with contributions from both upstream communities. My fork keeps their Git history, MIT license, and authorship visible while concentrating my own work on a practical red terminal dashboard, exact app shortcuts, compact device information, and a notification tray shaped around how I use the phone every day.", features: ["Red terminal dashboard and wallpaper Home surface", "Fixed installed-app shortcuts and command-first navigation", "Compact weather and live system monitoring", "Anchored notification tray with manual and five-minute clearing", "Preserved upstream history, license, and developer attribution"] },
  { slug: "bridgeforge", title: "BridgeForge", eyebrow: "Unreal and Blender ecosystem", description: "A focused ecosystem concept for Unreal Engine and Blender creators—bringing scattered tools, learning, and community resources together.", image: "/projects/bridgeforge.png", imageAlt: "BridgeForge creator ecosystem artwork", category: "Game Dev", status: "Building", platforms: "Windows", repository: "https://github.com/mcographics/BridgeForge", private: true, tags: ["Unreal Engine", "Blender", "Creator tools"], purpose: "BridgeForge is a concept for connecting the practical parts of 3D creation: tools, learning, references, and community. The project is still taking shape, so this page records the direction without pretending the full platform is released.", features: ["Unreal creator workflows", "Blender-focused resources", "Learning and reference hub", "Community ecosystem concept"] },
  { slug: "grace-seek", title: "Grace Seek", eyebrow: "Bible study desktop app", description: "A Scripture exploration app combining Bible search and reading with Strong’s lexicon, original-language datasets, and atlas-style place lookup.", image: "/projects/grace-seek.png", imageAlt: "Grace Seek Bible study application artwork", category: "Faith-Based", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/Grace-Seek", private: true, tags: ["Bible study", "Strong’s", "Local datasets"], purpose: "Grace Seek is being shaped as a serious local study companion: a way to move between the Biblical text, language references, and places without losing the reader’s sense of context.", features: ["Bible search and reading", "Strong’s lexicon references", "Original-language datasets", "Atlas-style place lookup"] },
  { slug: "space-eye", title: "Space Eye", eyebrow: "Space awareness experiment", description: "A real-time space-awareness experience that visualizes the solar system, tracks cosmic activity, and gathers public UFO and orb-sighting data.", image: "/projects/space-eye.png", imageAlt: "Space Eye visualization artwork", category: "Experiments", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/Space_Eye", private: true, tags: ["JavaScript", "Visualization", "Public data"], purpose: "Space Eye combines scientific scale with the human urge to look up and ask questions. It is an exploratory visualization project, with public data and uncertainty kept distinct where the evidence is incomplete.", features: ["Solar-system visualization", "Cosmic activity tracking", "Public sighting data", "Exploratory visual interface"] },
  { slug: "tanyaos", title: "TanyaOS", eyebrow: "AI cognitive interface", description: "A modular AI operating-system concept connecting a language model with structured memory, morality, reasoning, and autonomous decision-making subsystems.", image: "/projects/tanya-os.png", imageAlt: "TanyaOS interface artwork", category: "Experiments", status: "Research project", platforms: "Research prototype", repository: "https://github.com/mcographics/TanyaOS", private: true, tags: ["Python", "React", "Cognitive AI"], purpose: "TanyaOS is a research direction for making AI systems more structured, inspectable, and purposeful. Memory, reasoning, values, and action are treated as separate concerns that need to be understood before they are combined.", features: ["Structured memory concepts", "Reasoning subsystem research", "Values and morality layer", "Modular AI interface"] },
  { slug: "workspaces", title: "WorkSpaces", eyebrow: "All-in-one creative workspace", description: "An all-in-one creative environment combining visual canvases, brainstorming, document writing, book formatting, and story architecture.", image: "/projects/workspaces.png", imageAlt: "WorkSpaces creative environment artwork", category: "Creative", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/WorkSpaces", private: true, tags: ["TypeScript", "Writing", "Visual canvas"], purpose: "WorkSpaces is for the messy middle of making something: when notes, images, drafts, scenes, and structure need to coexist. Its purpose is to let a creator move between those modes without scattering the project across disconnected tools.", features: ["Visual project canvases", "Document and book writing", "Story architecture", "Local creative workspace"] },
  { slug: "project-database", title: "Project Database", eyebrow: "Project organization desktop app", description: "A local-first desktop workspace for organizing projects, documents, images, collections, timelines, and related creative assets in one secure place.", image: "/projects/project-database.png", imageAlt: "Project Database application artwork", category: "Apps", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/ProjectDatabase", tags: ["Electron", "React", "C++"], purpose: "Project Database gives each project a place where its files, references, timelines, and related ideas can remain connected. The foundation is local-first, so organization does not depend on a remote account.", features: ["Project and asset records", "Documents and image collections", "Timeline organization", "Secure local storage"] },
  { slug: "gamingbible", title: "GamingBible", eyebrow: "Gaming news desktop app", description: "A personalized desktop hub for gaming news, upcoming releases, studios, industry coverage, esports, hardware, and rumors—all gathered in one focused app.", image: "/projects/gamingbible.png", imageAlt: "GamingBible application artwork", category: "Apps", status: "In development", platforms: "Windows", repository: "https://github.com/mcographics/GamingBible", tags: ["Electron", "React", "Gaming news"], purpose: "GamingBible is a focused home for following the games and people that matter to a reader. It brings multiple kinds of coverage together while keeping personalization local and account-free.", features: ["Gaming news aggregation", "Release and studio tracking", "Esports and hardware coverage", "Local preferences and follows"] },
  { slug: "character-profile-maker", title: "Character Profile Maker", eyebrow: "Character design workspace", description: "A flexible character-building workspace for creating detailed visual profiles, organizing reference views, importing artwork, and exporting polished character sheets.", image: "/projects/character-profile-maker.png", imageAlt: "Character Profile Maker artwork", category: "Creative", status: "In development", platforms: "Windows", tags: ["Character design", "Worldbuilding", "Export tools"], purpose: "Character Profile Maker helps turn scattered references and design decisions into a coherent record. It is meant for creators who want their characters’ visual identity, notes, and variations in one editable workspace.", features: ["Detailed character profiles", "Reference-view organization", "Artwork importing", "Polished character-sheet export"] },
  { slug: "bible-recorder-note-taker", title: "Bible Recorder & Note Taker", eyebrow: "Android Bible study and audio notes", description: "A focused Android study workspace for recording teaching, capturing Audio Snaps, linking notes to Scripture, and keeping study history in one place.", image: "/projects/bible-recorder-banner.png", imageAlt: "Bible Recorder and Note Taker banner showing a Bible, microphone, and warm study imagery", shareImage: "/projects/bible-recorder-banner.png", shareImageAlt: "Bible Recorder and Note Taker Android study app banner", category: "Faith-Based", status: "Release available", platforms: "Android 7.0+", repository: "https://github.com/mcographics/Bible-Recorder-Note-Taker", tags: ["Android", "React", "Bible study", "Audio Snap", "Google Drive"], purpose: "Bible Recorder & Note Taker is designed for the moment a sermon, study, or personal reflection becomes worth keeping. The reference-led interface puts a large recording console, waveform, quick capture actions, Scripture, and linked notes in the same rounded workspace. It starts locally so a user can record and study without waiting for a network, while the connected account path is designed to sync personal study metadata through Firebase and keep user-owned recordings in Google Drive.", features: ["Reference-led recording console with timer and waveform", "One-tap Audio Snaps linked to the exact recording moment", "Bundled Bible reader with copy and add-to-note actions", "Notes, bookmarks, Library, and honest empty states", "Google sign-in with Firebase metadata sync and user-owned Drive storage"], featureDetails: ["The dark navy console keeps the timer, transport controls, waveform, and current note visible together, with rounded edges and selective gold accents instead of gradients.", "Audio Snap preserves the preceding rolling audio window and timestamp so an important sentence can be revisited from the recording timeline. Transcription remains unavailable until a transcription service is connected.", "The current app includes a structured Geneva 1560 reader with book, chapter, and verse navigation, plus copy-selected, copy-chapter, and add-to-note workflows.", "Search and Notes are built from the user’s actual local records; the clean first-run state does not seed fake notes, bookmarks, or sample sessions.", "Firebase Auth/Firestore is the account and metadata layer. Recordings are intended for the signed-in user’s own Google Drive rather than a shared Firebase Storage bucket."], screenshots: [
    { src: "/projects/bible-recorder-note-taker-screens/01-recording.png", label: "Recording", alt: "Bible Recorder and Note Taker Android recording console with timer, waveform, transport controls, and quick actions" },
    { src: "/projects/bible-recorder-note-taker-screens/02-bible-reader.png", label: "Bible reader", alt: "Bible Recorder and Note Taker Android Bible reader showing John chapter 3" },
    { src: "/projects/bible-recorder-note-taker-screens/03-notes.png", label: "Notes", alt: "Bible Recorder and Note Taker Android Notes screen with a clean empty state" },
    { src: "/projects/bible-recorder-note-taker-screens/04-search.png", label: "Search", alt: "Bible Recorder and Note Taker Android Search screen with Notes, Audio Snaps, and Scripture filters" },
  ], screenshotEyebrow: "Captured from the installed Android build", screenshotDescription: "These are direct screenshots from the connected Samsung SM-G781W. The workspace is intentionally clean; no sample study or fake notes are seeded.", release: { version: "1.0.0", downloadUrl: "https://github.com/mcographics/Bible-Recorder-Note-Taker/releases/download/v1.0.0/Bible-Recorder-Note-Taker-1.0.0.apk", releaseUrl: "https://github.com/mcographics/Bible-Recorder-Note-Taker/releases/tag/v1.0.0" }, releaseHeading: "Keep the moment.", releaseDescription: "Bible Recorder & Note Taker 1.0.0 is available as a direct APK for Android 7.0 and newer. The build follows the reference-led dark study layout and keeps the first-run workspace free of fabricated content.", releasePlatform: "Android 7.0+", releaseSmallText: "Signed release APK · GitHub distribution", journalSlug: "bible-recorder-note-taker-1-0-0", journalHeading: "Record what matters. Keep the moment.", journalDescription: "Read the detailed release story: the reference-led redesign, recording and Audio Snap workflow, Bible reader, clean data boundaries, Google sign-in, user-owned Drive storage, and what remains before a wider store release." },
];

export const projectDetailSlugs = projectDetails.map((project) => project.slug);
