import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "../../SiteHeader";
import WordsOfYeshuaGallery from "./WordsOfYeshuaGallery";

const siteUrl = "https://mcographics.github.io";
const projectUrl = `${siteUrl}/projects/words-of-yeshua/`;
const repositoryUrl = "https://github.com/mcographics/WordsofYeshua";
const releaseUrl = "https://github.com/mcographics/WordsofYeshua/releases/tag/v0.5.3";
const downloadUrl = "https://github.com/mcographics/WordsofYeshua/releases/download/v0.5.3/Words-of-Yeshua-Setup-0.5.3.exe";
const coverUrl = `${siteUrl}/projects/words-of-yeshua-slides/viewingmode/lightmode/00-words-of-yeshua-cover.png`;

export const metadata: Metadata = {
  title: "Words of Yeshua — Christ-Centred Scripture Study App | Majestic Creations",
  description: "A local-first Windows Scripture study companion for exploring the words of Yeshua in complete KJV chapter context.",
  alternates: { canonical: "/projects/words-of-yeshua/" },
  openGraph: { type: "website", url: projectUrl, siteName: "Majestic Creations", title: "Words of Yeshua — Christ-Centred Scripture Study App", description: "Explore the words of Yeshua inside complete KJV chapter context with a private, account-free Windows reader.", images: [{ url: coverUrl, width: 1181, height: 822, alt: "Words of Yeshua Scripture study cover artwork" }] },
  twitter: { card: "summary_large_image", title: "Words of Yeshua — Christ-Centred Scripture Study App", description: "A local-first Windows Scripture study companion.", images: [coverUrl] },
};

const softwareApplication = {
  "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Words of Yeshua", url: projectUrl, image: coverUrl,
  screenshot: ["01_cropped", "06_cropped", "08_cropped"].map((name) => `${siteUrl}/projects/words-of-yeshua-slides/viewingmode/lightmode/words_of_yeshua_${name}.png`),
  description: "A Christ-centred, local-first Bible reader and study companion for exploring the words of Yeshua in scriptural context.", applicationCategory: "EducationalApplication", applicationSubCategory: "Christian Scripture study application", operatingSystem: "Windows 10 or newer", softwareVersion: "0.5.3", datePublished: "2026-08-28", isAccessibleForFree: true, offers: { "@type": "Offer", price: "0", priceCurrency: "CAD", availability: "https://schema.org/InStock" }, downloadUrl, installUrl: downloadUrl,
  featureList: ["Complete KJV chapter context", "Focused exploration of the words of Yeshua", "Offline-first local reading", "Account-free private use", "Search, saved passages, and reading settings"], author: { "@type": "Person", name: "Kenneth Salmon", url: `${siteUrl}/about/` }, publisher: { "@type": "Organization", name: "Majestic Creations", url: siteUrl }, sameAs: repositoryUrl,
};

export default function WordsOfYeshuaPage() {
  return (
    <main className="product-page words-yeshua-product" id="top">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareApplication).replaceAll("<", "\\u003c") }} />
      <SiteHeader className="product-header" actionHref={repositoryUrl} actionLabel="View source" actionIcon="↗" />
      <section className="product-hero">
        <div className="product-hero-copy"><Link className="product-back" href="/#work">← All projects</Link><p className="section-kicker">Featured faith-based application</p><h1>Words of<br /><em>Yeshua.</em></h1><p className="product-deck">A quiet, Christ-centred study companion for returning to the words of Jesus in their complete King James Version chapter context—local-first, account-free, and built for careful reading.</p><div className="product-hero-actions"><a className="button primary" href="#downloads">Download the app <span>↓</span></a><a className="button ghost" href={repositoryUrl} target="_blank" rel="noreferrer">GitHub repository <span>↗</span></a></div><dl className="product-facts"><div><dt>Release</dt><dd>0.5.3</dd></div><div><dt>Price</dt><dd>Free</dd></div><div><dt>Account</dt><dd>Never</dd></div><div><dt>Offline</dt><dd>Yes</dd></div></dl></div>
        <figure className="product-cover"><img src="/projects/words-of-yeshua-slides/viewingmode/lightmode/00-words-of-yeshua-cover.png" alt="Words of Yeshua Scripture study cover artwork" /><figcaption><span>Scripture · Context · Reflection</span><strong>Read His words in context.</strong></figcaption></figure>
      </section>
      <nav className="product-quick-downloads" aria-label="Quick download options"><div><span>Ready to study?</span><strong>Choose the official release</strong></div><a className="button primary" href={downloadUrl}><span>Windows x64</span><small>EXE · v0.5.3</small><b>Download ↓</b></a><a className="button ghost" href={releaseUrl} target="_blank" rel="noreferrer"><span>Release notes</span><small>GitHub · v0.5.3</small><b>Read notes ↗</b></a><a className="button ghost" href="#gallery"><span>Application preview</span><small>10 supplied captures</small><b>View gallery ↓</b></a></nav>
      <section className="product-introduction" aria-labelledby="product-purpose"><div><p className="section-kicker">Context before commentary</p><h2 id="product-purpose">Begin with His words. Continue into the chapter.</h2></div><div><p>A single quotation can invite attention, but the surrounding chapter shows the audience, question, warning, parable, confrontation, or promise around it. Words of Yeshua gives the reader a focused way to find those sayings and keep reading into the complete KJV passage.</p><p>The application is designed as a quiet aid to Scripture study, not as a replacement for the Bible and not as a source of invented teaching. Biblical text, interface guidance, and any supporting reflection remain distinct.</p></div></section>
      <section className="product-gallery-section" id="gallery" aria-labelledby="product-gallery-heading"><header><p className="section-kicker">Application preview · Light Mode</p><h2 id="product-gallery-heading">A still place for serious reading.</h2><p>Explore the supplied Light Mode captures from the home screen, study controls, passage search, saved passages, and complete chapter reading experience.</p></header><WordsOfYeshuaGallery /></section>
      <section className="product-features" aria-labelledby="product-features-heading"><header><p className="section-kicker">Made for study</p><h2 id="product-features-heading">Keep the text central.</h2></header><div className="product-feature-grid"><article><span>01</span><h3>Words in context</h3><p>Move from focused sayings into complete KJV chapters so the surrounding passage remains part of the reading experience.</p></article><article><span>02</span><h3>Explore Scripture</h3><p>Use the study surfaces to browse, search passages, and return to the parts of Scripture you are considering.</p></article><article><span>03</span><h3>Save what matters</h3><p>Keep selected passages available for later review without turning a private reading practice into a public profile.</p></article><article><span>04</span><h3>Shape the reading room</h3><p>Adjust display, reading layout, study details, and window settings to create a calmer desktop environment.</p></article></div></section>
      <section className="product-privacy" aria-labelledby="product-privacy-heading"><div><p className="section-kicker">Free, private, and local-first</p><h2 id="product-privacy-heading">Study without creating a profile.</h2></div><div className="privacy-commitments"><p>Words of Yeshua is built for account-free, local reading. The Windows application keeps the study experience on the reader’s device and does not require a web account or subscription.</p><ul><li>Read bundled Scripture without depending on an online session.</li><li>Use saved passages and reading preferences locally.</li><li>No advertising profile, subscription, or paid feature is required.</li><li>Scripture remains identifiable and distinct from application presentation.</li></ul><p className="privacy-note">The app is a study companion. Its interface and supporting material do not replace the authority or provenance of the Biblical text.</p></div></section>
      <section className="product-downloads" id="downloads" aria-labelledby="downloads-heading"><header><p className="section-kicker">Official release · Windows</p><h2 id="downloads-heading">Choose the current build.</h2><p>Words of Yeshua v0.5.3 is available as a Windows x64 installer through the project’s GitHub Release.</p></header><div className="platform-table" role="table" aria-label="Words of Yeshua platform availability"><div className="platform-table-heading" role="row"><span role="columnheader">Platform</span><span role="columnheader">Version</span><span role="columnheader">Status</span><span role="columnheader">Download</span></div><div className="platform-row" role="row"><span role="cell"><strong>Windows x64</strong><small>Unsigned per-user installer</small></span><span role="cell">0.5.3</span><span role="cell">Stable release</span><span role="cell"><a className="platform-download" href={downloadUrl}>Download EXE ↓</a></span></div><div className="platform-row" role="row"><span role="cell"><strong>Android, Linux, iOS</strong><small>No public build listed</small></span><span role="cell">—</span><span role="cell">Not released</span><span role="cell"><span className="unavailable"><i />Not released</span></span></div></div><div className="download-grid"><article><div><span className="download-platform">Windows x64</span><strong>0.5.3</strong><small>Stable · approximately 130 MiB</small></div><p>The installer is unsigned, so Windows SmartScreen may show “Unknown publisher.” Confirm that the filename and source are correct before proceeding.</p><a className="button primary" href={downloadUrl}>Download EXE <span>↓</span></a><a href={releaseUrl} target="_blank" rel="noreferrer">Release notes ↗</a></article><article><div><span className="download-platform">Source and history</span><strong>GitHub</strong><small>Public repository and releases</small></div><p>Review the source project, release notes, and the current published artifact from the official repository.</p><a className="button ghost" href={repositoryUrl} target="_blank" rel="noreferrer">Open repository <span>↗</span></a><a href={releaseUrl} target="_blank" rel="noreferrer">View v0.5.3 release ↗</a></article></div></section>
      <section className="product-related" aria-labelledby="related-heading"><div><p className="section-kicker">From the journal</p><h2 id="related-heading">Reading His words in context.</h2><p>Read the story behind Words of Yeshua v0.5.2 and the decision to make context, provenance, and quiet local reading central to the application.</p><a className="button ghost" href="/blog/words-of-yeshua-v0-5-2/">Read the release story <span>→</span></a></div><img src="/projects/words-of-yeshua.png" alt="Words of Yeshua Scripture study application artwork" /></section>
      <footer className="about-footer"><Link className="brand" href="/"><img className="brand-logo" src="/brand/majestic-lion.png" alt="" /><span>MAJESTIC <b>CREATIONS</b></span></Link><p>Apps · Games · Worlds · Ideas</p><div><Link href="/#work">Projects</Link><Link href="/blog">Blog</Link><Link href="/about">About Me</Link><Link href="/contact">Contact Us</Link></div><small>© {new Date().getFullYear()} Majestic Creations. Built independently in Gatineau, Québec.</small></footer>
    </main>
  );
}
